---
# tasks file for roles/database
- name: Run app
  docker_container:
    name: "backend_{{ item }}"
    image: bubuuu/tp-devops-simple-api:latest
    pull: yes
    env_file: /home/admin/.env
    networks:
      - name: db_api
      - name: api_front_proxy
    container_default_behavior: compatibility
    networks_cli_compatible: no
  loop: [1, 2]