services:
    backend:
        build: ./java
        container_name: backendTP1
        networks:
            - proxy-back
            - back-bdd
        env_file: ".env"
        depends_on:
            - database

    database:
        build: ./postgres
        container_name: dbTP1
        networks:
            - back-bdd
        env_file: ".env"
        volumes:
            - ./data:/var/lib/postgresql/data

    httpd: 
        build: ./server
        container_name: proxyTP1
        ports:
            - 80:80
        networks:
            - proxy-back
        depends_on:
            - backend

networks:
    proxy-back:
    back-bdd:
