---
# tasks file for roles/database
- name: Run front
  docker_container:
    name: front
    image: bubuuu/tp-front:latest
    pull: yes
    env_file: /home/admin/.env
    networks:
      - name: api_front_proxy
    container_default_behavior: compatibility
    networks_cli_compatible: no