- hosts: all
  gather_facts: true
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
  roles:
    - docker
    - copy
    - network
    - database
    - app
    - proxy