---
# tasks file for roles/database
- name: Run postgres
  docker_container:
    name: database
    image: bubuuu/tp-postgres:latest
    pull: yes
    volumes:
      - /data:/var/lib/postgresql/data
    env_file: /home/admin/.env
    networks:
      - name: db_api
    container_default_behavior: compatibility
    networks_cli_compatible: no