---
# tasks file for roles/proxy
- name: Run HTTPD
  docker_container:
    name: httpd
    image: bubuuu/tp-httpd:latest
    exposed_ports:
      - "80"
    ports:
      - 80:80
    networks:
      - name: api_proxy
    container_default_behavior: compatibility
    networks_cli_compatible: no
    comparisons:
      image: ignore # do not restart containers with older versions of the image