---
# tasks file for roles/proxy
- name: Run HTTPD
  docker_container:
    name: httpd
    image: bubuuu/tp-httpd:latest
    pull: yes
    exposed_ports:
      - "80"
      - "8080"
    ports:
      - 80:80
      - 8080:8080
    networks:
      # - name: api_proxy
      - name: api_front_proxy
    container_default_behavior: compatibility
    networks_cli_compatible: no