name: CI devops 2025 #Nom du workflow
on: #Se déclenche au moment du ...
  push: #push sur ...
    branches: #Les branches qui sont listées ci-dessous.
      - main
      - develop
  pull_request:

jobs: #Lorsqu'il se déclenche, run ces jobs
  test-backend: #Nom d'un job
    runs-on: ubuntu-22.04 #Distrib sur laquelle va run le job
    steps: #Les différentes étapes du job. Chacune doit contenir un uses ou un run
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image and push backend
        uses: docker/build-push-action@v3
        with:
          context: ./java
          tags: ${{secrets.DOCKERHUB_USERNAME}}/tp-devops-simple-api:latest
          push: ${{ github.ref == 'refs/heads/main' }}

      - name: Build image and push database
        uses: docker/build-push-action@v3
        with:
          context: ./postgres
          tags: ${{secrets.DOCKERHUB_USERNAME}}/tp-postgres:latest
          push: ${{ github.ref == 'refs/heads/main' }}

      - name: Build image and push httpd
        uses: docker/build-push-action@v3
        with:
          context: ./server
          tags: ${{secrets.DOCKERHUB_USERNAME}}/tp-httpd:latest
          push: ${{ github.ref == 'refs/heads/main' }}

      