name: Push docker #Nom du workflow
on: #Se déclenche au moment du ...
  workflow_run: #push sur ...
    workflows: [CI devops 2025]
    types:
      - completed
  pull_request:

jobs: #Lorsqu'il se déclenche, run ces jobs
  build-and-push-docker-image: #Nom d'un job
    runs-on: ubuntu-22.04 #Distrib sur laquelle va run le job
    if: github.event.workflow_run.head_branch == 'main' # Vérifie si la branche est main
    steps: #Les différentes étapes du job. Chacune doit contenir un uses ou un run
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3 #On se log à docker hub
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image and push backend
        uses: docker/build-push-action@v3
        with:
          context: ./java
          tags: ${{secrets.DOCKERHUB_USERNAME}}/tp-devops-simple-api:latest
          push: ${{ github.ref == 'refs/heads/main' }}

      - name: Build image and push database
        uses: docker/build-push-action@v3
        with:
          context: ./postgres
          tags: ${{secrets.DOCKERHUB_USERNAME}}/tp-postgres:latest
          push: ${{ github.ref == 'refs/heads/main' }}

      - name: Build image and push httpd
        uses: docker/build-push-action@v3
        with:
          context: ./server
          tags: ${{secrets.DOCKERHUB_USERNAME}}/tp-httpd:latest
          push: ${{ github.ref == 'refs/heads/main' }}